using System;
using System.IO;
using System.Threading;
using BepInEx.Configuration;
using BepInEx.Logging;

namespace Landoria.Shared
{
    // Reloads the mod configuration after its file changes on disk.
    internal static class ConfigWatcher
    {
        private const int ReloadDelayMilliseconds = 250;
        private const int MaximumReloadAttempts = 5;

        private static ConfigFile config;
        private static string configPath;
        private static ManualLogSource logger;
        private static FileSystemWatcher watcher;
        private static long lastChangeTicks;
        private static int reloadPending;
        private static int reloadAttempts;
        private static long ignoredWriteTicks;
        private static string displayName;
        private static Action restoreDefaults;
        private static Action applyConfiguration;

        // Starts watching the active configuration file.
        internal static void Initialize(
            ConfigFile configFile,
            ManualLogSource logSource,
            string configurationDisplayName,
            Action restoreDefaultsAction,
            Action applyConfigurationAction = null)
        {
            Dispose();
            config = configFile;
            logger = logSource;
            displayName = configurationDisplayName;
            restoreDefaults = restoreDefaultsAction;
            applyConfiguration = applyConfigurationAction;
            configPath = Path.GetFullPath(config.ConfigFilePath);
            watcher = new FileSystemWatcher(
                Path.GetDirectoryName(configPath), Path.GetFileName(configPath));
            watcher.NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.Size |
                                   NotifyFilters.CreationTime | NotifyFilters.FileName;
            watcher.Changed += OnChanged;
            watcher.Created += OnChanged;
            watcher.Deleted += OnChanged;
            watcher.Renamed += OnRenamed;
            watcher.EnableRaisingEvents = true;
        }

        // Ignores notifications produced by a setting changed inside the game.
        internal static void IgnoreCurrentFileVersion()
        {
            if (string.IsNullOrEmpty(configPath) || !File.Exists(configPath))
            {
                return;
            }

            try
            {
                Interlocked.Exchange(
                    ref ignoredWriteTicks, File.GetLastWriteTimeUtc(configPath).Ticks);
                Interlocked.Exchange(ref reloadPending, 0);
            }
            catch (IOException)
            {
                logger?.LogDebug("Could not mark the internal configuration write.");
            }
        }

        // Reloads a pending change safely from Unity's main thread.
        internal static void Update()
        {
            if (Volatile.Read(ref reloadPending) == 0 || !ReloadDelayElapsed())
            {
                return;
            }

            Interlocked.Exchange(ref reloadPending, 0);
            try
            {
                bool recreated = !File.Exists(configPath);
                if (recreated)
                {
                    restoreDefaults?.Invoke();
                }
                else
                {
                    config.Reload();
                }

                applyConfiguration?.Invoke();
                reloadAttempts = 0;
                logger.LogInfo(recreated
                    ? "Recreated the deleted configuration with default values."
                    : "Reloaded configuration after a file change.");
                ShowReloadMessage(recreated);
            }
            catch (Exception exception)
            {
                RetryReload(exception);
            }
        }

        // Stops watching and releases operating-system resources.
        internal static void Dispose()
        {
            if (watcher != null)
            {
                watcher.EnableRaisingEvents = false;
                watcher.Dispose();
                watcher = null;
            }

            Interlocked.Exchange(ref reloadPending, 0);
            Interlocked.Exchange(ref ignoredWriteTicks, 0);
            reloadAttempts = 0;
            displayName = null;
            restoreDefaults = null;
            applyConfiguration = null;
        }

        // Records a normal file-system change for the main thread.
        private static void OnChanged(object sender, FileSystemEventArgs eventArgs)
        {
            QueueReload();
        }

        // Records a file replacement performed through a rename operation.
        private static void OnRenamed(object sender, RenamedEventArgs eventArgs)
        {
            QueueReload();
        }

        // Debounces repeated notifications generated by one file save.
        private static void QueueReload()
        {
            if (IsIgnoredWrite())
            {
                return;
            }

            Interlocked.Exchange(ref lastChangeTicks, DateTime.UtcNow.Ticks);
            Interlocked.Exchange(ref reloadPending, 1);
            reloadAttempts = 0;
        }

        // Identifies the file version most recently saved by the mod itself.
        private static bool IsIgnoredWrite()
        {
            try
            {
                long writeTicks = File.Exists(configPath)
                    ? File.GetLastWriteTimeUtc(configPath).Ticks
                    : 0;
                return writeTicks != 0 &&
                       writeTicks == Interlocked.Read(ref ignoredWriteTicks);
            }
            catch (IOException)
            {
                return false;
            }
        }

        // Checks whether the editor has finished writing the file.
        private static bool ReloadDelayElapsed()
        {
            long elapsed = DateTime.UtcNow.Ticks -
                           Interlocked.Read(ref lastChangeTicks);
            return elapsed >= TimeSpan.TicksPerMillisecond * ReloadDelayMilliseconds;
        }

        // Retries temporary file access failures without blocking Unity.
        private static void RetryReload(Exception exception)
        {
            reloadAttempts++;
            logger.LogWarning($"Configuration reload failed: {exception.Message}");
            if (reloadAttempts < MaximumReloadAttempts)
            {
                Interlocked.Exchange(ref lastChangeTicks, DateTime.UtcNow.Ticks);
                Interlocked.Exchange(ref reloadPending, 1);
            }
        }

        // Notifies the local player that the new settings are active.
        private static void ShowReloadMessage(bool recreated)
        {
            Player.m_localPlayer?.Message(
                MessageHud.MessageType.TopLeft,
                recreated
                    ? $"{displayName} configuration restored to defaults."
                    : $"{displayName} configuration reloaded.");
        }

    }
}
